version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "monthly"
