version: "3.9"
services:
  backend:
    build: backend
    ports:
      - "3000:80"

  web:
    build:
      context: web
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "3001:80"
    depends_on:
      - backend
