version: "3.9"
services:
  backend:
    build: backend/CbtBackend

    ports:
      - 3000:80

  web:
    build:
      context: web
      args:
        VITE_API_URL: http://localhost:3000

    depends_on:
      - backend

    ports:
      - 3001:80
