version: "3.9"

services:
  db:
    image: postgres:14-alpine

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build: backend/CbtBackend

    depends_on:
      - db

    environment:
      db__ConnectionString: Host=db:5432;Database=postgres;Username=postgres;Password=postgres

    ports:
      - 127.0.0.1:3000:80

  web:
    build:
      context: web
      args:
        VITE_API_URL: http://localhost:3000

    depends_on:
      - backend

    ports:
      - 127.0.0.1:3001:80
