openapi: 3.0.1
info:
  title: Team-CBT API
  description: "This is an API for Team-CBT web app"
  version: 1.0.0
servers:
  - url: https://teamcbt.com/v1
  - url: http://teamcbt.com/v1
tags:
  - name: user
    description: Operations about user
  - name: session
    description: Operations about session
  - name: evaluation
    description: Operations about evaluation
  - name: statistics
    description: Operations about statistics

paths:
  /session:
    post:
      tags:
        - session
      summary: Add a new session
      operationId: addSession
      security:
        - teamcbt_auth:
            - write:session
            - read:session
  /session/findByStatus:
    get:
      tags:
        - session
      summary: Finds Session by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findSessionByStatus
      security:
        - teamcbt_auth:
            - write:session
            - read:session
  /session/findByUserId:
    get:
      tags:
        - session
      summary: Finds Session by UserId
      operationId: findSessionByUserId
      security:
        - teamcbt_auth:
            - write:session
            - read:session
  /session/{sessionId}:
    get:
      tags:
        - session
      summary: Find Session by Id
      description: Returns a single session
      operationId: getSessionById
      security:
        - api_key: []
    put:
      tags:
        - session
      summary: Updates a Session in the database with form data
      operationId: updateSessionWithForm
      security:
        - teamcbt_auth:
            - write:session
            - read:session
    delete:
      tags:
        - session
      summary: Deletes a session
      operationId: deleteSession
      security:
        - teamcbt_auth:
            - write:session
            - read:session
  /user:
    post:
      tags:
        - user
      summary: Register user
      description: Register user
      operationId: createUser
    get:
      tags:
        - user
      summary: get list of users
      operationId: getAllUsers
      security:
        - teamcbt_auth:
            - write:session
            - read:session
  /user/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
  /user/logout:
    post:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
  /user/{login}:
    get:
      tags:
        - user
      summary: Get user by login (email)
      operationId: getUserByEmail
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
  /evaluation:
    post:
      tags:
        - evaluation
      summary: Add a new evaluation
      operationId: addEvaluation
      security:
        - teamcbt_auth:
            - write:evaluation
            - read:evaluation
  /evaluation/findByStatus:
    get:
      tags:
        - evaluation
      summary: Finds Evaluation by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findEvaluationByStatus
      security:
        - teamcbt_auth:
            - write:evaluation
            - read:evaluation
  /evaluation/findByUserId:
    get:
      tags:
        - evaluation
      summary: Finds Evaluation by userId
      operationId: findEvaluationByuserId
      security:
        - teamcbt_auth:
            - write:evaluation
            - read:evaluation
  /evaluation/{evaluationId}:
    get:
      tags:
        - evaluation
      summary: Find Evaluation by Id
      description: Returns a single session
      operationId: getEvaluationById
      security:
        - api_key: []
    put:
      tags:
        - evaluation
      summary: Updates an Evaluation in the database with form data
      operationId: updateEvaluationWithForm
      security:
        - teamcbt_auth:
            - write:evaluation
            - read:evaluation
    delete:
      tags:
        - evaluation
      summary: Deletes an evaluation
      operationId: deleteEvaluation
      security:
        - teamcbt_auth:
            - write:evaluation
            - read:evaluation
  /statistics/{statisticId}:
    put:
      tags:
        - statistics
      summary: Update an existing statistic
      operationId: updateStatistics
      security:
        - teamcbt_auth:
            - write:statistics
            - read:statistics
  /statistics:
    post:
      tags:
        - statistics
      summary: Add a new statistic
      operationId: addStatistic
      security:
        - teamcbt_auth:
            - write:statistics
            - read:statistics
  /statistics/{login}:
    get:
      tags:
        - statistics
      summary: Get Statistics of a user
      description: Returns a statistics object
      operationId: getStatisticsByEmail
      security:
        - teamcbt_auth:
            - write:statistics
            - read:statistics
  /statistics/{userId}:
    get:
      tags:
        - statistics
      summary: Get Statistics of a user
      description: Returns a statistics object
      operationId: getStatisticsByUserId
      security:
        - teamcbt_auth:
            - write:statistics
            - read:statistics
components:
  securitySchemes:
    teamcbt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    api_key:
      type: apiKey
      name: api_key
      in: header
