name: backend-cd

on:
  push:
    branches: [main]
    paths: [backend/**]
  pull_request:
    branches: [main]
    paths: [backend/**]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Send a webhook event
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
