name: backend-ci

on:
  push:
    branches: [main]
    paths: [backend/**]
  pull_request:
    paths: [backend/**]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Run analyzer
        run: dotnet format --severity info --verify-no-changes

      - name: Build
        run: dotnet build
